### PR TITLE
Don't use input/outputs for tasks

### LINKED ISSUE #35: No such file or directory after upgrading to Gradle 4.2
I think this exception is related to `gradle-git-publish` when running on Gradle 4.2 -- or am I mistaken?

```
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:253)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:85)
	at java_util_concurrent_Callable$call$0.call(Unknown Source)
	at org.ajoberstar.grgit.operation.AddOp.call(AddOp.groovy:53)
	at org.ajoberstar.grgit.operation.AddOp.call(AddOp.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.ajoberstar.grgit.internal.OpSyntax.mapOperation(OpSyntax.groovy:33)
	at org.ajoberstar.grgit.internal.OpSyntax$mapOperation.callStatic(Unknown Source)
	at org.ajoberstar.grgit.Grgit.add(Grgit.groovy)
	at org.ajoberstar.grgit.Grgit$add$7.call(Unknown Source)
	at org.ajoberstar.gradle.git.publish.GitPublishPlugin$_createCommitTask_closure5$_closure15.doCall(GitPublishPlugin.groovy:141)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:700)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:673)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 94 more
Caused by: java.io.IOException: No such file or directory
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.newTempFile(ObjectDirectoryInserter.java:273)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.toTemp(ObjectDirectoryInserter.java:200)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:144)

```

See log after the upgrade to Gradle 4.2 with complete stacktrace at https://junit.ci.cloudbees.com/blue/organizations/jenkins/JUnit5/detail/JUnit5/2230/pipeline

Or this is the latest one with more debug information:
https://junit.ci.cloudbees.com/blue/rest/organizations/jenkins/pipelines/JUnit5/runs/2260/log/?start=0

### PR DESCRIPTION
**Pull request by ajoberstar**
As of Gradle 4.2 [1], when execution of a task begins, any "stale" outputs
will be deleted. All files under build and any declared outputs are
considered managed by Gradle. If other files happen to be in there,
Gradle will delete them.

The reset task did not declare any outputs, but created the
build/gitPublish directory and cloned the repo in there. When the copy
task rolls around, which is a built in task with declared
inputs/outputs, it sees some that cloned repo as stale files in its
output directory, since the copy task didn't put them there. Since they
are also under build, Gradle considers itself the owner and thinks it's
safe to delete them.

Since the inputs/outputs of the tasks in this plugin both overlap and
sometimes aren't clear files in / files out situations, it is easier for
now to drop using them altogether.

This commit drops the use of the Copy task, in favor of a ad-hoc task
that uses project.copy. This was the only task that had any
inputs/outputs declared before, so this issue should no longer be able
to present.

This fixes #35.

[1] https://docs.gradle.org/4.2/release-notes.html#safer-handling-of-stale-output-files

### CODE REVIEW

File: src/main/groovy/org/ajoberstar/gradle/git/publish/GitPublishPlugin.groovy [hunk 1]
```diff
@@ -71,6 +71,10 @@ class GitPublishPlugin implements Plugin<Project> {
     task.with {
       group = 'publishing'
       description = 'Prepares a git repo for new content to be generated.'
+
+      // creates/clones the repo
+      outputs.dir(extension.repoDir)
```
Comment (wolfs) [inline src/main/groovy/org/ajoberstar/gradle/git/publish/GitPublishPlugin.groovy]: I guess you also should do `outputs.upToDateWhen { false }` to make sure the task is always executed. Given that is has no inputs that is what would happen if the output directory contents would not change. Alternatively, you could also add the inputs to the task (git commit hash, branch, remote?) if that is possible. Same goes for the other tasks in here.
In the future, we may provide you with a way to declare that there should not be any up-to-date checks for a task, so you don't pay the performance penalty of checking all the files in the repository for changes.

**Review by wolfs — CHANGES_REQUESTED** [review]
I left some comments about also using `upToDateWhen { false }`. You could also consider to not use the `Copy` task, but use [`Project.copy`](https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:copy(org.gradle.api.Action)) instead. Then not a single one of your tasks would be using incremental build.

**Comment by ajoberstar** [comment]
Thanks @wolfs. I wasn't quite sure how to deal with these tasks that work in the same directory or the ones that are doing remote work rather than outputting a concrete file. I might be able to come up with some inputs, but maybe it does make more sense to drop the Copy task. I'll look into this more this weekend.

**Comment by ajoberstar** [comment]
I've reworked this to use project.copy. Seems like the most straightforward option at this point.
